#Setting up environment

In [ ]:
#import
import numpy as np

In [ ]:
#creating environment


#defining states
num_rows=11
num_columns=11

q_values=np.zeros((num_rows,num_columns,4))

#defining actions
#0=up,1=right, 2=down, 3=left

actions=['up','right','down','left']


#rewards matrix
rewards=np.full((num_rows,num_columns),-100.)
rewards[0, 5] = 100. #set the reward for the packaging area (i.e., the goal) to 100

#define aisle locations (i.e., white squares) for rows 1 through 9
aisles = {} #store locations in a dictionary
aisles[1] = [i for i in range(1, 10)]
aisles[2] = [1, 7, 9]
aisles[3] = [i for i in range(1, 8)]
aisles[3].append(9)
aisles[4] = [3, 7]
aisles[5] = [i for i in range(11)]
aisles[6] = [5]
aisles[7] = [i for i in range(1, 10)]
aisles[8] = [3, 7]
aisles[9] = [i for i in range(11)]

#set the rewards for all aisle locations (i.e., white squares)
for row_index in range(1, 10):
  for column_index in aisles[row_index]:
    rewards[row_index, column_index] = -1.

#print rewards matrix
for row in rewards:
  print(row)

[-100. -100. -100. -100. -100.  100. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100.   -1. -100. -100. -100. -100. -100.   -1. -100.   -1. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.   -1. -100.]
[-100. -100. -100.   -1. -100. -100. -100.   -1. -100. -100. -100.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-100. -100. -100. -100. -100.   -1. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100. -100. -100.   -1. -100. -100. -100.   -1. -100. -100. -100.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]


#Training

In [ ]:
#helper functions


#terminal state
def is_terminal_state(cur_row,cur_col):
  if(rewards[cur_row,cur_col]==-1.):
    return False
  else:
    return True

#get random starting index
def get_start_index():
  cur_row=np.random.randint(num_rows)
  cur_col=np.random.randint(num_columns)

  while(is_terminal_state(cur_row,cur_col)):
    cur_row=np.random.randint(num_rows)
    cur_col=np.random.randint(num_columns)
  return cur_row, cur_col

#next action by epsilon greedy method
def get_next_action(cur_row,cur_col, epsilon):
  r=np.random.random()
  if(r<epsilon):
    return np.argmax(q_values[cur_row,cur_col])
  else:
     return np.random.randint(4)

#update new row and column values
def get_next_state(cur_row,cur_col,action):
  new_row, new_col=cur_row, cur_col
  if action==0 and cur_row>0:
    new_row-=1
  elif action==1 and cur_col<num_columns-1:
    new_col+=1
  elif action==2 and cur_row<num_rows-1:
    new_row+=1
  elif action==3 and cur_col>0:
    new_col-=1
  return new_row,new_col

#finding thee shortest path
def get_shortest_path(start_row,start_col):
  if(is_terminal_state(start_row,start_col)):
    return []
  else:
    short_path=[]
    cur_row,cur_col=start_row,start_col
    short_path.append([cur_row,cur_col])
    while not(is_terminal_state(cur_row,cur_col)):
      action=get_next_action(cur_row,cur_col,1.0)
      cur_row,cur_col=get_next_state(cur_row,cur_col,action)
      short_path.append([cur_row,cur_col])
  return short_path



In [ ]:
#training agent

#training parameters
epsilon=0.9
gamma=0.9
alpha=0.9

for episode in range(1000):
  #initialise
  row,col=get_start_index()

  while(not(is_terminal_state(row,col))):
    action=get_next_action(row,col,epsilon)

    old_row,old_col=row,col
    row,col=get_next_state(row,col,action)

    rew=rewards[row,col]
    td=rew+(gamma*np.max(q_values[row,col]))-q_values[old_row,old_col,action]

    new_q=q_values[old_row,old_col,action]+(alpha*td)
    q_values[old_row,old_col,action]=new_q

print('Trained!!!')

Trained!!!


#Get shortest paths

In [ ]:
get_shortest_path(1,5)

[[1, 5], [0, 5]]

In [ ]:
get_shortest_path(9,5)

[[9, 5],
 [9, 4],
 [9, 3],
 [8, 3],
 [7, 3],
 [7, 4],
 [7, 5],
 [6, 5],
 [5, 5],
 [5, 4],
 [5, 3],
 [4, 3],
 [3, 3],
 [3, 2],
 [3, 1],
 [2, 1],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [0, 5]]